version: "3"

services:
    redis:
      image: redis:latest
      ports:
        - "6379:6379"

    app: &app
      restart: always
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "80:80"
      volumes:
        - ./app:/app
      command: >
        sh -c "python manage.py wait_for_db &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:80"
      env_file:
        - app_env_variables.env
      depends_on:
        - db
        - redis
        - rabbitmq

    db:
      image: postgres:12-alpine
      env_file:
        - database_env_variables.env

    rabbitmq: # Rabbit message queue
      image: rabbitmq:3.8.5-alpine

    celery_worker: #Clery worker service
      <<: *app
      command: celery -A app worker --loglevel=info
      ports: []
      depends_on:
        - db
        - rabbitmq

    channels:
      build: .
      command: daphne -b 0.0.0.0 -p 8001 app.asgi:application
      volumes:
        - ./app:/app
      ports:
        - "8001:8001"
      links:
        - redis