version: "3"

services:
    redis:
      image: redis:latest
      ports:
        - "6379:6379"

    app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8000:8000"
      volumes:
        - ./app:/app
      command: >
        sh -c "python manage.py wait_for_db &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
      env_file:
        - app_env_variables.env
      depends_on:
        - db
        - redis

    db:
      image: postgres:12-alpine
      env_file:
        - database_env_variables.env

    channels:
      build: .
      command: daphne -b 0.0.0.0 -p 8001 app.asgi:application
      volumes:
        - ./app:/app
      ports:
        - "8001:8001"
      links:
        - redis