from django.urls import path

from . import views

app_name = 'institute'

urlpatterns = [
    # Institute license related url
    path('get-discount-coupon',
         views.GetInstituteDiscountCouponView.as_view(),
         name='get-discount-coupon'),
    path('institute-license-list',
         views.InstituteLicenseListView.as_view(),
         name="institute-license-list"),
    path('institute-license-detail',
         views.InstituteLicenseDetailView.as_view(),
         name="institute-license-detail"),
    path('select-license',
         views.InstituteSelectLicenseView.as_view(),
         name='select-license'),
    path('create-order',
         views.InstituteCreateOrderView.as_view(),
         name='create-order'),
    path('razorpay-payment-callback',
         views.RazorpayPaymentCallbackView.as_view(),
         name='razorpay-payment-callback'),
    path('razorpay-webhook-callback',
         views.RazorpayWebhookCallbackView.as_view(),
         name='razorpay-webhook-callback'),
    path('<slug:institute_slug>/get-license-purchased',
         views.InstituteLicenseOrderDetailsView.as_view(),
         name='get-license-purchased'),
    path('<slug:institute_slug>/check-license-exists',
         views.InstituteUnexpiredPaidLicenseExistsView.as_view(),
         name='check-license-exists'),
    # Institute related url
    path('create',
         views.CreateInstituteView.as_view(),
         name="create"),
    path('detail/<slug:institute_slug>',
         views.InstituteFullDetailsView.as_view(),
         name="detail"),
    # Institute permission
    path('<slug:institute_slug>/provide-permission',
         views.InstituteProvidePermissionView.as_view(),
         name="provide_permission"),
    path('<slug:institute_slug>/accept-delete-permission',
         views.InstitutePermissionAcceptDeleteView.as_view(),
         name="accept_delete_permission"),
    path('<slug:institute_slug>/<slug:role>/get-user-list',
         views.InstitutePermittedUserListView.as_view(),
         name="get_permission_list"),
    path('institute-min-details-teacher-admin',
         views.InstituteMinDetailsTeacherView.as_view(),
         name="institute-min-details-teacher-admin"),
    path('joined-institutes-teacher',
         views.InstituteJoinedMinDetailsTeacherView.as_view(),
         name="joined-institutes-teacher"),
    path('pending-institute-invites-teacher',
         views.InstitutePendingInviteMinDetailsTeacherView.as_view(),
         name="pending-institute-invites-teacher"),
    # Institute class
    path('<slug:institute_slug>/create-class',
         views.CreateClassView.as_view(),
         name='create-class'),
    path('<slug:class_slug>/delete-class',
         views.DeleteClassView.as_view(),
         name='delete-class'),
    path('add-class-permission',
         views.ProvideClassPermissionView.as_view(),
         name='add-class-permission'),
    path('<slug:class_slug>/list-permitted-class-incharge',
         views.ListPermittedClassInchargeView.as_view(),
         name='list-permitted-class-incharge'),
    path('<slug:class_slug>/has-class-perm',
         views.CheckClassPermView.as_view(),
         name='has-class-perm'),
    path('<slug:class_slug>/create-subject',
         views.CreateSubjectView.as_view(),
         name='create-subject'),
    # Institute section
    path('<slug:class_slug>/create-section',
         views.CreateSectionView.as_view(),
         name='create-section')
]
