# Generated by Django 3.0.6 on 2020-05-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepictures',
            name='public_profile_picture',
            field=models.BooleanField(default=False, verbose_name='PublicProfilePicture'),
        ),
    ]
