# Generated by Django 3.0.5 on 2020-04-29 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.ProhibitNullCharactersValidator], verbose_name='Subject name'),
        ),
    ]
