# Generated by Django 3.0.5 on 2020-04-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200429_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='email',
            new_name='user',
        ),
    ]
