# Generated by Django 3.0.5 on 2020-04-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200429_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('is_active', 'user_is_active'), ('is_staff', 'user_is_staff'), ('is_student', 'user_is_student'), ('is_teacher', 'user_is_teacher'))},
        ),
    ]
